name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'demo/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Build use-nft
        run: yarn install --frozen-lockfile && yarn build

      - name: Build demo/
        run: cd demo && yarn install --frozen-lockfile && yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: demo/dist
